name: build

on:
  push:
    branches: [ main ]
    paths:
      - '!README.md'
      - '!docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run staticcheck
        run: staticcheck ./...

      - name: run vet
        run: go vet ./...

      - name: run tests
        run: go test ./...

      - name: build
        run: go build -v ./...
